### ISSUE TITLE
feature: providing details in each callback would be handy

### ISSUE THREAD

**Issue by devmuaz** [Baseflow/flutter_swipe_detector#1]
Hi, there!
I just saw this awesome package and i was wondering if it possible to provide the gesture details in each callback!
This would be very handy especially if we wanna use these details to perform some other actions depending on the details themself!

if PRs are welcomed! i would gladly happy to write one that may possibly add such feature!
Thank You

**Comment by jopmiddelkamp** [comment]
Hi @devmuaz,

Yes, please feel free to provide a PR with this feature. 

Kind regards,

**Comment by jopmiddelkamp** [comment]
Version [2.0.0](https://pub.dev/packages/flutter_swipe_detector/versions/2.0.0) has been released. 

Issue will be closed.
